### PR TITLE
Disable to the force press in simulator when 'UseTrack Force' is enable

### PR DESCRIPTION
**Pull request by nakajijapan**
# Problem

The debug icon hides In some simulator when user touches the one.

# The cause

The force press gesture is recognized as normal tap gesture in simulator when 'UseTrack Force' is enable.

# Solution

I disabled to the force press gesture in the simulator.

### CODE REVIEW

**Comment by malt03** [comment]
LGTM.
However, please use `targetEnvironment(simulator)` instead of `TARGET_IPHONE_SIMULATOR`.
And you should not initialize `FourcePressGestureRecognizer`.

**Comment by malt03** [comment]
@nakajijapan

**Comment by nakajijapan** [comment]
:bow:

**Comment by nakajijapan** [comment]
@malt03 I just fixed some items pointed out!

**Pull request merged**
